#!c:\users\cgx\onedrive - teesside university\desktop\mlprojectend2end\crop_recom\scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
